name: Hello-World
on: workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
      - name: Steps Hello Worl !
        run: echo hello, world !
      